- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx if RHEL
    ansible.builtin.dnf:
     name: nginx
     state: installed
    when: ansible_os-family == "RedHat"
  - name: install nginx if ubuntu
    ansible.builtin.apt:
     name: nginx
     state: installed
    when: ansible_os-family == "Debian"